# Spring properties
spring:
  # Dev is active by default. This value can be overwritten by java arg param 
  profiles:
    active: heroku
  application:
    name: integrador
  messages:
    basename: bundles/languageBundle

logging:
  level.root: INFO
  file: integradorapi.log